import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppProvider } from "./AuthContext";
import { Sidebar } from "./components/demo/side-bar";
import PlayerBar from "./components/demo/play-bar";
import StoreProvider from "./storeContext";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <AppProvider>
          <StoreProvider>
            {" "}
            <div className="flex h-screen bg-linear-to-br from-gray-900 via-purple-900 to-black overflow-hidden">
              <Sidebar />
              {children}
              <PlayerBar />
            </div>
          </StoreProvider>
        </AppProvider>
      </body>
    </html>
  );
}
